### ISSUE TITLE
updating fails

### ISSUE THREAD

**Issue by pcnate** [simonkberg/atom-check-updates#3]
```
pcnate@debian:~$ acu 
 ✨ atom-check-updates v0.1.1 ✨   

Retrieving information about your distro...
- Detected as running on a Debian-based distro. 

Checking for installed stable version...
/home/pcnate/.npm/lib/node_modules/atom-check-updates/lib/acu.js:81
               resolve(version[1]);
                              ^

TypeError: Cannot read property '1' of null
   at /home/pcnate/.npm/lib/node_modules/atom-check-updates/lib/acu.js:81:32
   at ChildProcess.exithandler (child_process.js:204:7)
   at emitTwo (events.js:87:13)
   at ChildProcess.emit (events.js:172:7)
   at maybeClose (internal/child_process.js:818:16)
   at Socket.<anonymous> (internal/child_process.js:319:11)
   at emitOne (events.js:77:13)
   at Socket.emit (events.js:169:7)
   at Pipe._onclose (net.js:469:12)
```

**Comment by simonkberg** [comment]
Thanks! Fixed in v0.1.2 `npm i -g atom-check-updates@0.1.2`
